sbatch -A was122 /home/apoorvk/trials/scripts/pore1.seed1.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore1.seed2.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore1.seed3.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore2.seed1.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore2.seed2.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore2.seed3.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore3.seed1.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore3.seed2.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore3.seed3.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore4.seed1.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore4.seed2.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore4.seed3.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore5.seed1.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore5.seed2.sb
sbatch -A was122 /home/apoorvk/trials/scripts/pore5.seed3.sb